config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists do
    resources :bookmarks, only: [ :new, :create]
  end
  resources :bookmarks, only: :destroy

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  # validates :comment, length: { mimimum: 6 }

end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
  has_many :bookmarks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    def index
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(list: @list)
  end

  def create

    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
    redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path

  end

  private
   def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)

    # rescue ActionController::ParameterMissing => error
    #   json_response({ message: error }, :unprocessable_entity)
    #   redirect_to list_path(lists/new)
    #   return nil
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all


  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
    redirect_to list_path(@list)
    else
      redirect_to lists_path(new)
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new

  end

  private
   def list_params
    params.require(:list).permit(:name, :photo)

    # rescue ActionController::ParameterMissing => error
    #   json_response({ message: error }, :unprocessable_entity)
    #   redirect_to list_path(lists/new)
    #   return nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/new.html.erb
<h1>bookmark#create</h1>
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.label :comment %>
  <%= f.text_field :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/show.html.erb
show.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!DOCTYPE html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsWatchList1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <section class="glass">
        <div class="dashboard">
          <div class="user">
            <%= yield %>
          </div>
        </div>


       </section>
        <div class="circle1"></div>

        <div class="circle2"></div>
    </main>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
<h1 class="text-center text-secondary"> My Movie Lists</h1>


<div class="dashboard">
  <div class="cards">
    <% @lists.each do |list| %>
    <% if list.photo.attached? %>
    <div class="card rounded" style="width: 10rem;">
      <img class="card-img-top rounded-top rounded-2" src="<%= cl_image_path list.photo.key, height: 300, width: 400, crop: :fill %>">
      <div class="card-body">
        <h5 class="card-title"><%= link_to list.name, list_path(list) %></h5>
      </div>
    </div>
    <% else %>
    <div class="card" style="width: 10rem;">
      <img class="card-img-top" src="<%= cl_image_path 'mpcbkybwarsywo7znb5z', height: 300, width: 400, crop: :fill %>">
      <div class="card-body">
        <h5 class="card-title"><%= link_to list.name, list_path(list) %></h5>
      </div>

    </div>
    <% end %>
    <% end %>
  </div>
</div>
<div class="p-2">
  <%=  link_to 'Create a new list', list_path('new') %>
</div>
</div>

app/views/lists/new.html.erb
<h1>List#create</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1 class="text-center text-secondary"> <%=  @list.name %></h1>

<br>
<div class="cards">
<div class="p-2"
  <div class="row">
<div class="col-sm-16 d-flex">
<%  @list.movies.each do |movie| %>

<div class="card rounded-1" style="width: 18rem;">
  <img class="card-img-top" src="<%= movie.poster_url %>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= movie.title %></h5>
    <p class="card-text"><%= movie.overview %> </p>
    <%  bookmark = Bookmark.find_by(list: @list, movie: movie) %>
    <a href="#" class="btn btn-primary"><%= link_to "Remove", bookmark_path(bookmark),
  method: :delete, data: { confirm: "Are you sure?" } %></a>
  </div>
</div>
</div>
</div>

<% end %>
</div>
</div>

<br>


<%=  link_to 'Create a new bookmark', new_list_bookmark_path(@list.id) %>
<br>
<%= link_to 'Home', lists_path %>